@startuml

skinparam rectangle {
  BackgroundColor #FFFFFF
  BorderColor #000000
  FontSize 14
}

skinparam frame {
  BackgroundColor #E8F4F8
  BorderColor #2980B9
  FontSize 14
}

skinparam folder {
  BackgroundColor #FFF9E6
  BorderColor #F39C12
  FontSize 14
}

skinparam component {
  BackgroundColor #E8F8F5
  BorderColor #27AE60
  FontSize 19
}

skinparam interface {
  BackgroundColor transparent
  BorderColor transparent
}

component "<<AtomicRosNodeClassifier>>\
RealSenseCamera" as node {
  portin "trigger_callback" as sub_1
  portin "supervision_trigger_callback" as sub_2
  portout " " as pub_1
  portout " " as pub_2
  portout " " as pub_3
}

frame "sub_1" as topic_disassembly_status {
  rectangle "**std_msgs/msg/String**" as t_sub_1
}

frame "sub_2" as topic_supervision_status {
  rectangle "**std_msgs/msg/String**" as t_sub_2
}

frame "pub_1" as topic_camera_color_image_raw {
  rectangle "**sensor_msgs/msg/Image**" as t_pub_1
}

frame "pub_2" as topic_camera_aligned_depth_to_color_image_raw {
  rectangle "**sensor_msgs/msg/Image**" as t_pub_2
}

frame "pub_3" as topic_camera_color_camera_info {
  rectangle "**sensor_msgs/msg/CameraInfo**" as t_pub_3
}

topic_disassembly_status -[#blue,bold]-> sub_1
topic_supervision_status -[#blue,bold]-> sub_2
pub_1 -[#green,bold]-> topic_camera_color_image_raw
pub_2 -[#green,bold]-> topic_camera_aligned_depth_to_color_image_raw
pub_3 -[#green,bold]-> topic_camera_color_camera_info

@enduml